import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Contact from "@/components/contact";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fawas am",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <NavHeader /> */}
      <Header />

      <body className={inter.className}>{children}</body>
      <Contact />
    </html>
  );
}
